name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what you expected
    validations:
      required: true
